/*
 * generated by Xtext 2.25.0
 */
package org.example.domainmodel.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link DomainmodelWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractDomainmodelWebModule extends DefaultWebModule {

}
