/*
 * generated by Xtext 2.25.0
 */
package org.example.domainmodel.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.example.domainmodel.DomainmodelRuntimeModule;
import org.example.domainmodel.DomainmodelStandaloneSetup;
import org.example.domainmodel.ide.DomainmodelIdeModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class DomainmodelWebSetup extends DomainmodelStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DomainmodelRuntimeModule(), new DomainmodelIdeModule(), new DomainmodelWebModule()));
	}
	
}
